### PR TITLE
Set generic family name from fontconfig when available

### PR DESCRIPTION
**Pull request by declantsien**
This MR is tring to initialize fontdb with available generic family names from fontconfig.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Thanks. Not sure if it will work as expected. Hard to test. But should be fine.

**Comment by declantsien** [comment]
With a test config `FONTCONFIG_FILE=/tmp/test.conf cargo run`
```
fn main() {
    let mut db = fontdb::Database::new();
    db.load_system_fonts();
    println!("serif: {:?} ", db.family_name(&fontdb::Family::Serif));
}
```
**Currently, it only reads `Alias`,  `Match` is not supported.**

/tmp/test.conf
``` 
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>

<!-- Fallback fonts preference order -->
 <alias>
  <family>sans-serif</family>
  <prefer>
   <family>Noto Sans</family>
   <family>Open Sans</family>
   <family>Droid Sans</family>
   <family>Roboto</family>
   <family>Tholoth</family>
   <family>Noto Sans Arabic</family>
  </prefer>
 </alias>
 <alias>
  <family>serif</family>
  <prefer>
   <family>Noto Serif</family>
   <family>Droid Serif</family>
   <family>Roboto Slab</family>
   <family>Tholoth</family>
   <family>Noto Sans Arabic</family>
  </prefer>
 </alias>
 <alias>
  <family>monospace</family>
  <prefer>
   <family>Noto Sans Mono</family>
   <family>Inconsolata</family>
   <family>Droid Sans Mono</family>
   <family>Roboto Mono</family>
  </prefer>
 </alias>

</fontconfig>
```
Copied from archwiki https://wiki.archlinux.org/title/Font_configuration/Examples#Default_fonts

**Comment by RazrFalcon** [comment]
@declantsien is this patch fixes #24 ?

**Comment by declantsien** [comment]
Yevhenii Reizner ***@***.***> writes:

I think it does, as per the issue description:

> when the fontconfig feature is enabled, would read and interpret the
> settings from fontconfig to determine the fonts that alias "Sans
> Serif, "Serif", "Cursive", etc.

Worth mention that we currently only support `alias` part of fontconfig.
The `match` parts are not used.

**Comment by RazrFalcon** [comment]
Thanks.

**Pull request merged**
