### PR TITLE
Upgrade `ttf-parser` to `0.20`

### PR DESCRIPTION
**Pull request by MarijnS95**

### CODE REVIEW

**Comment by RazrFalcon** [comment]
I usually upgrade dependencies before a release. Are you looking for a new fontdb release with ttf-parser 0.20?

**Comment by MarijnS95** [comment]
Yeah, together with a release for https://github.com/alexheretic/ab-glyph/pull/90 (out of your control, just mentioning it) to not have duplicate `ttf-parser` dependencies via your `rustybuzz 0.11` release.

**Comment by RazrFalcon** [comment]
I see. I will update and publish it later.

**Comment by MarijnS95** [comment]
Having both crates released at the same pace (when identical dependency bumps are concerned) is appreciated :ok_hand:

**Comment by MarijnS95** [comment]
Still looking forward to this :slightly_smiling_face:

**Comment by RazrFalcon** [comment]
Done.

**Pull request closed without merging**
